version: "3.8"

secrets:
  postgres_user:
    file: ./secrets/postgres_user.txt
  postgres_password:
    file: ./secrets/postgres_password.txt
  mail_user:
    file: ./secrets/mail_user.txt
  mail_password:
    file: ./secrets/mail_password.txt
  secretkey:
    file: ./secrets/secretkey.txt

services:
  nginx:
    restart: always
    build: ./nginx
    ports:
      - "80:80"
    volumes:
      - ./web/static:/static
    links:
      - web:web

  web:
    restart: always
    build: ./web
    links:
      - postgres:postgres
    secrets:
      - postgres_user
      - postgres_password
      - mail_user
      - mail_password
      - secretkey
    environment:
      POSTGRES_DB: openvolunteer-db
      DATABASE_PORT: 5432
      POSTGRES_USER_FILE: /run/secrets/postgres_user
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
      MAIL_SERVER: smtp.gmail.com
      MAIL_PORT: 465
      MAIL_USE_TLS: "False"
      MAIL_USE_SSL: "True"
      MAIL_USER_FILE: /run/secrets/mail_user
      MAIL_PASSWORD_FILE: /run/secrets/mail_password
      SECRET_KEY_FILE: /run/secrets/secretkey
    expose:
      - "8000"
    depends_on:
      - postgres
    command: >
      sh -c "python3 ./create_db.py &&
             gunicorn -w 2 -b :8000 app:app"

  postgres:
    restart: always
    image: postgres:latest
    volumes:
      - db-data:/var/lib/postgresql/data
    secrets:
      - postgres_user
      - postgres_password
    environment:
      POSTGRES_DB: openvolunteer-db
      POSTGRES_USER_FILE: /run/secrets/postgres_user
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
    expose:
      - "5432"
    ports:
      - "5432:5432"

volumes:
  db-data: {}
