version: "3.8"

services:
  nginx:
    restart: always
    build: ./nginx
    ports:
      - "80:80"
    volumes:
      - ./web/static:/static
    links:
      - web:web

  web:
    restart: always
    build: ./web
    links:
      - postgres:postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      DATABASE_PORT: 5432
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      MAIL_SERVER: ${MAIL_SERVER}
      MAIL_PORT: ${MAIL_PORT}
      MAIL_USE_TLS: ${MAIL_USE_TLS}
      MAIL_USE_SSL: ${MAIL_USE_SSL}
      MAIL_USER: ${MAIL_USER}
      MAIL_PASSWORD: ${MAIL_PASSWORD}
      SECRET_KEY: ${SECRET_KEY}
    expose:
      - "8000"
    depends_on:
      - postgres
    command: >
      sh -c "python3 ./create_db.py &&
             gunicorn -w 2 -b :8000 app:app"

  postgres:
    restart: always
    image: postgres:latest
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    expose:
      - "5432"
    ports:
      - "5432:5432"

volumes:
  db-data: {}
