services:
  nginx:
    restart: always
    build: ./nginx
    ports:
      - "443:443"
    volumes:
      - ./web/static:/static
      - ssl_volume:/etc/nginx/ssl/
    links:
      - web:web

  web:
    restart: always
    build: ./web
    links:
      - postgres:postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      DATABASE_PORT: 5432
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      MAIL_SERVER: ${MAIL_SERVER}
      MAIL_PORT: ${MAIL_PORT}
      MAIL_USE_TLS: ${MAIL_USE_TLS}
      MAIL_USE_SSL: ${MAIL_USE_SSL}
      MAIL_USER: ${MAIL_USER}
      MAIL_PASSWORD: ${MAIL_PASSWORD}
      SECRET_KEY: ${SECRET_KEY}
      SSL_CERT_PATH: ${SSL_CERT_PATH}
      SSL_KEY_PATH: ${SSL_KEY_PATH}
    volumes:
      - ssl_volume:/ssl
    expose:
      - "443:8000"
    depends_on:
      - postgres
    command: >
      sh -c "python3 ./create_db.py &&
             gunicorn -w 2 -b :443 app:app --certfile ${SSL_CERT_PATH} --keyfile ${SSL_KEY_PATH}"
    develop:
      watch:
        - action: sync+restart
          path: ./web
          target: /
        - action: rebuild
          path: ./web/requirements.txt

  postgres:
    restart: always
    image: postgres:latest
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    expose:
      - "5432"
    ports:
      - "5432:5432"

volumes:
  ssl_volume:
  db-data: {}
