version: "3.8"

services:
  openvolunteer:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:4000"
    environment:
      - DB_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - openvolunteer-volume:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  openvolunteer-volume:
